n = input('Digite algo: ')
print('A variável é do tipo {} '.format(type(n)))
print('A variável possue apenas espaços? {}'.format(n.isspace()))
print('A variável é numérica? {}'.format(n.isnumeric()))
print('A variável é alfabetica? {}'.format(n.isalpha()))
print('A variável é alfanumérica? {}'.format(n.isalnum()))
print('A variável é formada por letras maiúsculas? {}'.format(n.isupper()))
print('A variável é formada por letras minúsculas? {}'.format(n.islower()))
print('A variável é captalizado? {}'.format(n.istitle()))
